import { app, BrowserWindow, dialog, Menu } from 'electron';
import { ChildProcess, spawn } from 'node:child_process';
import path from 'node:path';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const apiUrl = 'http://127.0.0.1:5202';
let apiProcess: ChildProcess | null = null;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

const waitForApi = async (): Promise<void> => {
  for (let attempt = 0; attempt < 60; attempt += 1) {
    try {
      const response = await fetch(`${apiUrl}/api/health`);
      if (response.ok) return;
    } catch {
      // The API may still be starting, so try again briefly.
    }

    await new Promise((resolve) => setTimeout(resolve, 250));
  }

  throw new Error('The bundled API did not start.');
};

const startBundledApi = async (): Promise<void> => {
  if (!app.isPackaged) return;

  const apiPath = path.join(
    process.resourcesPath,
    'api',
    'RiskDesk.Api.exe',
  );

  apiProcess = spawn(apiPath, ['--urls', apiUrl], {
    cwd: path.dirname(apiPath),
    env: {
      ...process.env,
      ASPNETCORE_ENVIRONMENT: 'Production',
    },
    stdio: 'ignore',
    windowsHide: true,
  });

  apiProcess.once('exit', () => {
    apiProcess = null;
  });

  await waitForApi();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(async () => {
  try {
    await startBundledApi();
    Menu.setApplicationMenu(null);
    createWindow();
  } catch (error) {
    console.error('Could not start the bundled API:', error);
    dialog.showErrorBox(
      'Unable to start Florida Landfall Detector',
      'The local analysis service could not be started. Close any other copy of the application and try again.',
    );
    app.quit();
  }
});

app.on('before-quit', () => {
  apiProcess?.kill();
  apiProcess = null;
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
